name: challenge01

on:
  push:
    branches:
      - challenge01

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print date
        run: date
  job2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print date
        run: date
  job3:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print date
        run: date
  job4:
    runs-on: ubuntu-latest
    needs: [ job1, job2, job3 ]
    steps:
      - uses: actions/checkout@v2
      - name: Print success
        run: echo "Success!"
