name: custom

on:
  push:
    branches: [ "main" ]

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print the local environment variables
        run: |
          echo "Print the local environment variables on Ubuntu"
          env | sort
  job2:
    name: Second job
    runs-on: windows-latest
    needs: job1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print the local environment variables
        run: |
          echo "Print the local environment variables on Windows"
          "Get-ChildItem Env: | Sort-Object Name"