name: Secrets

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code and look for secrets
        uses: actions/checkout@v2
        run: |
          echo "Checking out code"
          echo "Looking for secrets"
          echo "Found secrets"
          echo "Secrets found: ${{ secrets.THIS_IS_A_SECRET }}"