name: Secrets

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add secrets to environment
        run: |
          echo "Checking out code"
          echo "Looking for secrets"
          echo "Found secrets"
          echo "Secrets found using YAML syntax: ${{ secrets.THIS_IS_A_SECRET }}"
          echo "Secrets found using bash syntax: ${{ env.THIS_IS_A_SECRET }}"
        with:
          secret: ${{ secrets.THIS_IS_A_SECRET }}
